spring:
  redis:
    database: 1
    host: 1.117.5.70
    port: 6379
    password:
    lettuce:
      pool:
        min-idle: 8
        max-idle: 500
        max-active: 2000
        max-wait: 10000
server:
  port: 9091
